logging:
  level: INFO
  loggers:
    com.example.jhuerta: DEBUG

mySQLConfiguration:
  database:
    url: "jdbc:mysql://localhost:3306/appDB"
    driverClass: com.mysql.jdbc.Driver
    minSize: 1
    maxSize: 40
    user: "app_user"
    password: "My_Password_123"
    properties:
      charSet: "UTF-8"
    maxWaitForConnection: 1s
    checkConnectionWhileIdle: true
    checkConnectionOnBorrow: true
    evictionInterval: 10s
    minIdleTime: 1 minute
